# Generated by Django 2.2.1 on 2020-02-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://lh5.googleusercontent.com/proxy/v4DGgKq401Nf_qLRtK89avYhK6jj41bGvusvzItZ4y96fES3y48wJeeUN1119QVYWlO2YxredI0oOBomZ3XedVHlXyWMg8EYfiDcIA', max_length=500),
        ),
    ]
